Feature/81829 new fields project conversion
DFE-Digital/trams-data-api pull request #158
Opened 2022-03-02 09:44 UTC by HussenShambeshDfE

Additional Fields added to (...../v2/conversion-projects) endpoint

- New URN
- New LEA Estab / DfE Number
- New Academy UKPRN
- New UPIN (if possible)
- Trust UKPRN
- New Academy Name

Related Story: https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/81829

2022-03-03 14:59 UTC, mishraksantosh approved these changes

2022-03-04 13:24 UTC, MichaelDally requested changes
Requires Cypress test

2022-03-07 13:15 UTC, MartinWheelerMT commented on TramsDataApi/Migrations/TramsDb/20220303130816_ProposedAcademyAdditionalFields.cs
> +            _ = migrationBuilder.Sql(@"CREATE  VIEW sdd.vw_proposed_academy_additional_fields
Can you remove the comments from this view please, the table they are from implies the usage.

2022-03-07 14:00 UTC, MartinWheelerMT approved these changes

2022-03-07 14:04 UTC, MichaelDally approved these changes

2022-03-07 14:16 UTC, MartinWheelerMT approved these changes

2022-03-07 14:25 UTC, merged