Add fuzzy search
DFE-Digital/trams-data-api pull request #50
Opened 2021-07-01 09:38 UTC by nouriach

**Add a Fuzzy Search feature to when searching Trusts by Group Name.**

1. Update the SearchGroups() method in the TrustGateway to include Contains()
2. Add new Integration Test to check for when searching by just a partial GroupName
3. Add new Integration Test to check for when searching by all parameters and a partial GroupName

2021-07-01 16:18 UTC, RobertM905 commented on TramsDataApi.Test/Integration/TrustsIntegrationTests.cs
> +        private string GenerateRandomStringSuffix()
You could probably use the NBuilder random generator for this. :)

2021-07-01 16:33 UTC, RobertM905 commented on TramsDataApi/Gateways/TrustGateway.cs
> +                    g.GroupName.ToLower().Contains(groupToCheck) ||
I'm pretty sure `.Contains` is mapped to `LIKE` so is not case sensitive. 
Are you sure you need a ToLower here?

2021-07-01 16:35 UTC, RobertM905 commented on TramsDataApi.Test/Integration/TrustsIntegrationTests.cs
> +            var groupNamePartial = "Mygroupnam";
Might be worth having the search term have different upper and lower cases to ensure that the search is not case sensitive.

2021-07-02 10:47 UTC, LewisDaleUK requested changes

2021-07-13 08:04 UTC, LewisDaleUK approved these changes
Looks good to me :)

2021-07-13 08:06 UTC, merged